///
/// \file    sentinel_task_rtc_service.hpp
/// \brief   DS3231 RTC service task (1 Hz SQW-interrupt driven)
///
/// \details This header declares the RTC service FreeRTOS task. The task
///          programmes the DS3231 to emit a 1 Hz square wave on its INT/SQW
///          pin, takes that signal as a falling-edge GPIO interrupt on
///          \ref sentinel::resource::rtc_sqw_pin, and on each edge latches
///          the current time from the RTC over the arbitrated I²C bus.
///
///          The square-wave edge is generated by the same TCXO that
///          increments the DS3231's seconds register, so each interrupt is
///          phase-aligned to the real second rollover — the latched time is
///          always fresh rather than sampled at an arbitrary offset. The
///          interrupt also lets the MCU sleep between ticks instead of
///          polling the bus.
///
///          The most recent timestamp is published via \ref last_unix_time
///          for other tasks to consume (e.g. a future BLE Current Time
///          characteristic). This task does not set the RTC; initial/
///          authoritative time-setting belongs to the BLE sync path.
///
/// \author  galudino
/// \date    2026-05-24
/// \version 1.0 - Initial RTC service task
///

#ifndef SENTINEL_TASK_RTC_SERVICE_HPP
#define SENTINEL_TASK_RTC_SERVICE_HPP

#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
extern "C" {
#include <task.h>
}
#pragma GCC diagnostic pop

#include <cstdint>

namespace sentinel::task::rtc_service {

///
/// \brief Create and start the RTC service task.
///
/// \return \c pdPASS if the task was created successfully, otherwise the
///         \c xTaskCreate failure code.
///
BaseType_t task_create();

///
/// \brief RTC service task body. Configures the 1 Hz SQW interrupt, then
///        latches the current time on every tick. Created in main().
///
/// \param task_parameter Unused.
///
void task_function(void *task_parameter);

///
/// \brief FreeRTOS task handle for the RTC service task.
///
inline TaskHandle_t task_handle;

///
/// \brief Most recent Unix timestamp latched on a 1 Hz SQW tick.
///
/// \return Seconds since 1970-01-01 UTC as of the last tick, or \c 0 before
///         the first tick (or if the RTC time was unreadable). Backed by a
///         32-bit aligned value, so the read is atomic on Cortex-M without
///         a lock.
///
uint32_t last_unix_time() noexcept;

///
/// \brief Most recent DS3231 die temperature, in 0.01 °C.
///
/// \details Cached on the same cadence the time is latched. Consumed by the
///          device snapshot \c populate() (#36) so it never has to issue a
///          fresh I²C read of its own. Backed by a 16-bit aligned value, so the
///          cross-task read is atomic on Cortex-M without a lock.
///
/// \return Temperature in 0.01 °C as of the last successful read, or \c 0
///         before the first successful read.
///
int16_t last_temperature_centi_c() noexcept;

} // namespace sentinel::task::rtc_service

#endif /* SENTINEL_TASK_RTC_SERVICE_HPP */
